language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-26
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository
    - sys-img-armeabi-v7a-android-25
    - sys-img-armeabi-v7a-android-24

before_install:
 - chmod +x gradlew

script:
  - ./gradlew clean connectedCheck

after_success:
  - .buildscript/deploy_snapshot.sh

notifications:
  email: false

