plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-parcelize'
    id 'maven-publish'
    id 'org.jlleitschuh.gradle.ktlint'
    id 'org.jetbrains.dokka'
    id 'jacoco'
}

jacoco {
    toolVersion = "0.8.11"
}

tasks.withType(Test) {
    jacoco.includeNoLocationClasses = true
    jacoco.excludes = ['jdk.internal.*']
}

task jacocoTestReport(type: JacocoReport, dependsOn: ['testDebugUnitTest']) {
    reports {
        xml.required = true
        html.required = true
    }

    def fileFilter = ['**/R.class', '**/R$*.class', '**/BuildConfig.*', '**/Manifest*.*', '**/*Test*.*', 'android/**/*.*', '**/view/**']
    def buildDirFile = layout.buildDirectory.get().asFile
    def debugTree = fileTree(dir: "$buildDirFile/tmp/kotlin-classes/debug", excludes: fileFilter)
    def mainSrc = "$projectDir/src/main/java"

    sourceDirectories.setFrom(files([mainSrc]))
    classDirectories.setFrom(files([debugTree]))
    executionData.setFrom(fileTree(dir: buildDirFile, includes: [
            'jacoco/testDebugUnitTest.exec'
    ]))
}

task jacocoTestCoverageVerification(type: JacocoCoverageVerification, dependsOn: 'jacocoTestReport') {
    def fileFilter = ['**/R.class', '**/R$*.class', '**/BuildConfig.*', '**/Manifest*.*', '**/*Test*.*', 'android/**/*.*', '**/view/**']
    def buildDirFile = layout.buildDirectory.get().asFile
    def debugTree = fileTree(dir: "$buildDirFile/tmp/kotlin-classes/debug", excludes: fileFilter)
    classDirectories.setFrom(files([debugTree]))
    executionData.setFrom(fileTree(dir: buildDirFile, includes: [
            'jacoco/testDebugUnitTest.exec'
    ]))
    violationRules {
        rule {
            limit {
                minimum = 0.01
            }
        }
    }
}

group = 'com.nonzeroapps.whatisnewdialog'

android {
    namespace = 'com.nonzeroapps.whatisnewdialog'
    compileSdk 34
    defaultConfig {
        minSdk 21
        targetSdk 34
        versionCode 14
        versionName "1.2.4"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            consumerProguardFiles 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }

    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }

    publishing {
        singleVariant('release') {
            withSourcesJar()
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    androidTestImplementation('androidx.test.espresso:espresso-core:3.7.0', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.robolectric:robolectric:4.16.1'

    implementation 'androidx.appcompat:appcompat:1.8.0'
    implementation 'com.github.bumptech.glide:glide:5.0.7'
    annotationProcessor 'com.github.bumptech.glide:compiler:5.0.7'
    implementation 'androidx.palette:palette:1.0.0'
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release
                groupId = 'com.nonzeroapps.whatisnewdialog'
                artifactId = 'whatisnewdialog'
                version = '1.2.4'
            }
        }
    }
}