package com.nonzeroapps.whatisnewdialog

import android.os.Parcel
import android.os.Parcelable

/**
 * Writes this [Parcelable] to a [Parcel] and reads it back, returning the recreated instance.
 *
 * The `CREATOR` field generated by `@Parcelize` is resolved reflectively so that the production
 * model classes do not need to declare a companion object purely for test access.
 */
@Suppress("UNCHECKED_CAST")
inline fun <reified T : Parcelable> T.parcelRoundTrip(): T {
    val parcel = Parcel.obtain()
    try {
        writeToParcel(parcel, 0)
        parcel.setDataPosition(0)
        val creator = T::class.java.getField("CREATOR").get(null) as Parcelable.Creator<T>
        return creator.createFromParcel(parcel)
    } finally {
        parcel.recycle()
    }
}
